const products = [
  {
    id: 1,
    name: "Ramen",
    category: "animation",
    price: 10,
    imageSrc: "/assets/meal/ramen.png",
    imageAlt: "ramen ponyo sur la falaise",
    emporter: "Oui",
    livraison: "Oui",
    rating: 4,
    description:
      "Un bol de ramen qui danse avec les vagues de l'océan, accompagné de poissons en forme de poissons et d'algues qui fredonnent des mélodies joyeuses.",
  },
  {
    id: 2,
    name: "Spaghetti à la bolognaise",
    category: "animation",
    price: 15,
    imageSrc: "/assets/meal/spaghettis.png",
    imageAlt: "spaghetti la belle et le clochard",
    emporter: "Non",
    livraison: "Oui",
    rating: 5,
    description:
      "Une montagne de spaghettis qui s'entrelacent comme un baiser passionné sous un ciel de sauce tomate étoilé, avec deux boulettes de viande qui s'étreignent tendrement au sommet.",
  },
  {
    id: 3,
    name: "Ratatouille",
    category: "animation",
    price: 15,
    imageSrc: "/assets/meal/ratatouille.png",
    imageAlt: "ratatouille de ratatouille",
    emporter: "Oui",
    livraison: "Non",
    rating: 3,
    description:
      "Une danse colorée de légumes qui s'entremêlent avec grâce, créant une symphonie de saveurs qui mettra même le critique culinaire le plus sévère à genoux.",
  },
  {
    id: 4,
    name: "Gumbo",
    category: "animation",
    price: 17,
    imageSrc: "/assets/meal/gumbo.png",
    imageAlt: "gumbo de la princesse et la grenouille",
    emporter: "Oui",
    livraison: "Non",
    rating: 4,
    description:
      "Un chaudron magique débordant de crevettes dansantes, de saucisses qui swinguent et de légumes qui font le moonwalk, créant un tourbillon de saveurs cajun.",
  },
  {
    id: 5,
    name: "Haggis",
    category: "animation",
    price: 9,
    imageSrc: "/assets/meal/haggis.png",
    imageAlt: "haggis de rebelle",
    emporter: "Non",
    livraison: "Non",
    rating: 2,
    description:
      "Un plat courageux qui ose mélanger les traditions, avec un haggis écossais qui porte une flèche sur son dos et une pincée d'esprit rebelle.",
  },
  {
    id: 6,
    name: "Bao buns",
    category: "animation",
    price: 12,
    imageSrc: "/assets/meal/buns.png",
    imageAlt: "bao buns de bao",
    emporter: "Oui",
    livraison: "Non",
    rating: 5,
    description:
      "Des petits coussins moelleux qui cachent des secrets délicieux, comme des petites créatures farceuses qui vous font sourire à chaque bouchée.",
  },
  {
    id: 7,
    name: "Poulet frit",
    category: "film",
    price: 17,
    imageSrc: "/assets/meal/poulet.png",
    imageAlt: "poulet frit de la couleur des sentiments",
    emporter: "Non",
    livraison: "Non",
    rating: 4,
    description:
      "Un poulet croustillant qui porte avec fierté les couleurs de l'âme, avec une panure qui réconforte et une marinade qui guérit les cœurs brisés.",
  },
  {
    id: 8,
    name: "Pain des morts",
    category: "animation",
    price: 5,
    imageSrc: "/assets/meal/pain.png",
    imageAlt: "pain des morts de coco",
    emporter: "Oui",
    livraison: "Oui",
    rating: 3,
    description:
      "Un pain qui résonne avec l'écho des ancêtres, saupoudré de sucre comme les souvenirs doux-amers qui nous lient à nos racines.",
  },
  {
    id: 9,
    name: "Pizza",
    category: "film",
    price: 12,
    imageSrc: "/assets/meal/pizza.png",
    imageAlt: "pizza de mange prie aime",
    emporter: "Non",
    livraison: "Oui",
    rating: 5,
    description:
      "Une pizza qui capture l'essence de l'Italie, avec des ingrédients qui chantent une ode à la joie, à la spiritualité et à la passion.",
  },
  {
    id: 10,
    name: "Croissant et café",
    category: "film",
    price: 6,
    imageSrc: "/assets/meal/croissant.png",
    imageAlt: "croissant et café de diamants sur canapé",
    emporter: "Oui",
    livraison: "Oui",
    rating: 4,
    description:
      "Un croissant qui brille comme un diamant, trempé dans un café qui chuchote des secrets élégants, créant un petit-déjeuner digne des plus grandes stars de la haute couture.",
  },
];

export default products;
